# Generated by Django 3.0.5 on 2020-04-26 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import safm.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='No description provided.')),
                ('profile_picture', models.FileField(blank=True, default='default/pictures/pp.png', max_length=255, upload_to=safm.models.UserProfile.user_directory_path)),
                ('email_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
