# Generated by Django 3.0.5 on 2020-05-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='tone',
            new_name='key',
        ),
    ]
