# Generated by Django 3.0.7 on 2020-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0004_auto_20200527_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
    ]
