# Generated by Django 3.0.7 on 2020-06-15 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safm', '0005_sample_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSampleDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_download', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safm.Sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleForkTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_fork_to_base', to='safm.Sample')),
                ('sample_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_fork_to', to='safm.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleForkFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_fork_from_base', to='safm.Sample')),
                ('sample_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_fork_from', to='safm.Sample')),
            ],
        ),
    ]
