# Generated by Django 3.0.7 on 2020-06-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0006_sampleforkfrom_sampleforkto_usersampledownload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='nb_dl_unauthenticated',
            new_name='number_downloads',
        ),
    ]
