# Generated by Django 3.0.7 on 2020-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0007_auto_20200616_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='forks',
            field=models.ManyToManyField(related_name='_sample_forks_+', to='safm.Sample'),
        ),
    ]
