# Generated by Django 3.0.7 on 2020-07-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0008_sample_forks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleforkto',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sampleforkto',
            name='sample_to',
        ),
        migrations.DeleteModel(
            name='SampleForkFrom',
        ),
        migrations.DeleteModel(
            name='SampleForkTo',
        ),
    ]
