# Generated by Django 3.0.7 on 2020-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0009_auto_20200701_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='key',
            field=models.CharField(blank=True, choices=[('', 'None'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('min', 'Minor'), ('maj', 'Major')], default='', max_length=3),
        ),
    ]
