# Generated by Django 3.0.7 on 2020-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safm', '0011_auto_20200703_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='forks',
            field=models.ManyToManyField(related_name='forks_to', to='safm.Sample'),
        ),
    ]
