# TODO: If you make any changes to this file, checkout

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
# python linter and pep8 convention conformer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
        -   id: flake8
    # flake8 is notorious for being overly strict at times
    # to ignore some violations check here for use case
    # https://flake8.pycqa.org/en/latest/user/violations.html#ignoring-violations-with-flake8
