# Generated by Django 3.0.7 on 2020-07-14 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import safm_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=safm_api.models.Sample.sample_path)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tempo', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, choices=[(' ', 'None'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default=' ', max_length=1)),
                ('mode', models.CharField(blank=True, choices=[(' ', 'None'), ('min', 'Minor'), ('maj', 'Major')], default=' ', max_length=3)),
                ('description', models.TextField(blank=True, default='No description provided.')),
                ('datetime_upload', models.DateTimeField(auto_now_add=True)),
                ('number_downloads', models.PositiveIntegerField(default=0)),
                ('forks', models.ManyToManyField(related_name='forks_to', to='safm_api.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSampleDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_download', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safm_api.Sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='No description provided.')),
                ('profile_picture', models.FileField(blank=True, default='default/pictures/pp.png', max_length=255, upload_to=safm_api.models.UserProfile.profile_picture_path)),
                ('email_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='tags',
            field=models.ManyToManyField(to='safm_api.Tag'),
        ),
        migrations.AddField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
